### PR TITLE
Bump Facebook API version to v2.2

### PR DESCRIPTION
**Pull request by tinderhacker**

### CODE REVIEW

**Review by arvinio — COMMENTED** [review]
current version is 2.5. My PR adds regex for any version number

**Comment by mayeaux** [comment]
So is this guy working right now? I haven't touched these tinder things in ages

**Comment by arvinio** [comment]
Yeah I fixed it with my own PR which you've merged. This PR is obsolete though.

**Comment by gregbarcza** [comment]
Closing, since https://github.com/tinderjs/tinderauth/pull/11 fixed it.

**Pull request closed without merging**
